Add follow_link_fallback config option
renerocksai/telekasten.nvim pull request #172
Opened 2022-10-08 17:10 UTC by kurotych

## Proposed change

#171 

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Documentation update

## Additional information

- This PR fixes or closes issue: fixes 
- This PR is related to issue: #171 
- 
## Checklist

- [x] I am running the **latest** version of the plugin.
- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] The code has been formatted using Stylua (a `.stylua.toml` file is provided)
- [x] The code has been checked with luacheck (a `.luacheckrc` file is provided)
- [x] The `README.md` has been updated according to this change.
- [x] The `doc/telekasten.txt` helpfile has been updated according to this change.

2022-10-12 11:02 UTC, lambtho12 requested changes

2022-10-12 11:02 UTC, lambtho12 commented on doc/telekasten.txt
> +        Default: `nil`
We should maybe document the fact that when it defaults to `nil`, telekasten will simply use `xdg-open` or `open`.

2022-10-13 16:06 UTC, kurotych commented
Hello, @lambtho12.

Thank you for your response.
I've changed the configuring variable's name and behavior by your wishes. 
I agree that it looks easier just to ask the command.

2022-10-17 19:59 UTC, lambtho12 approved these changes
Awesome. Thank you and sorry for the delay!

2022-10-17 20:00 UTC, merged